version: "3"
services:
  backend4-service:
    container_name: backend4-container
    restart: always
    command: python manage.py runserver 0.0.0.0:8000 
    build: .  
    ports:
      - "9005:8000"
